name: Release

on:
  push:
    branches:
      - "ci"

permissions:
  contents: write
  id-token: write

jobs:
  publish-wasm:
    name: Publish WASM to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          key: publish-wasm

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'

      - name: Build WASM package
        run: make build-wasm

      - name: Package WASM artifact
        run: tar -czvf apcn-wasm.tar.gz pkg

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v7
        with:
          name: apcn-wasm
          path: apcn-wasm.tar.gz

      - name: Publish to NPM
        run: make publish-wasm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
